apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q237da3ct-go 
  janus-idp.io/tekton: q237da3ct-go
  backstage.io/kubernetes-id: q237da3ct-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q237da3ct-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  