apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: q237da3ct-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: q237da3ct-go 
  name: q237da3ct-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: q237da3ct-go 
